index:
   path: /
   controller: App\Controller\DefaultController::index
   
page_detaillée:
    path: /pageDetail
    controller: App\Controller\PageDetailController::detail

creer_profil:
   path: /creerprofil
   controller: App\Controller\UserController::create

liste_utilisateur:
   path: /listuser
   controller: App\Controller\UserController::index

edit_user:
   path: /user/edit/{id}
   controller: App\Controller\UserController::edit

admin_edit_user:
   path: /admin/user/edit/{id}
   controller: App\Controller\UserController::adminEdit

admin_user_delete:
   path: /admin/user/delete/{id}
   controller: App\Controller\UserController::delete