index:
   path: /
   controller: App\Controller\DefaultController::index
   
page_detaillée:
    path: /detailArticle
    controller: App\Controller\PageDetailController::detail


# ROUTE PROFIL USER
creer_profil:
   path: /creerprofil
   controller: App\Controller\UserController::create

liste_utilisateur:
   path: /listuser
   controller: App\Controller\UserController::index

edit_user:
   path: /user/edit/{id}
   controller: App\Controller\UserController::edit

admin_edit_user:
   path: /admin/user/edit/{id}
   controller: App\Controller\UserController::adminEdit

admin_user_delete:
   path: /admin/user/delete/{id}
   controller: App\Controller\UserController::delete


# ROUTE ARTICLES DE L'USER CONNECTÉ 
mes_articles:
    path: /mesArticles
    controller: App\Controller\PageMesArticlesController::mesArticles

supp_article:
    path: /mesArticles/delete/{id}
    controller: App\Controller\PageMesArticlesController::supprimerArticle

ajouter_article:
    path: /ajouterArticles/
    controller: App\Controller\PageMesArticlesController::ajouterArticle

modifier_article:
    path: /modifierArticle/{id}
    controller: App\Controller\PageMesArticlesController::modifierArticle

